server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: bank-app-search
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: bank_app_search
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    contexts: postgres

logging:
  level:
    org.zalando.logbook.Logbook: TRACE

logbook:
  format:
    style: http
