server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: bank-app-search
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: bank_app_search
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    contexts: postgres
  cloud:
    openfeign:
      client:
        config:
          operation-history:
            connect-timeout: 1000
            read-timeout: 4000
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.zalando.logbook.Logbook: TRACE

logbook:
  format:
    style: http

bank-app-search:
  min-rank: 0.05
  max-size-latest-results: 10
  integrations:
    operation-history:
      host: http://localhost:8081
  pools:
    latest-results-pool:
      pool-size: 10
      thread-timeout-seconds: 60
      queue-size: 1000
